import type { Conversation, DeliveryOrder, Driver, Incident, Vehicle } from "@/lib/types";

export const company = {
  name: "DevTesters Delivery's Granada",
  city: "Granada, Nicaragua",
  whatsappNumber: "+505 8888 1234",
  currency: "NIO",
};

export const drivers: Driver[] = [
  {
    id: "driver-luis",
    name: "Luis Rodríguez",
    initials: "LR",
    phone: "+505 8888 4590",
    vehicle: "Honda CB125F",
    vehiclePlate: "GR 23981",
    status: "en_servicio",
    rating: 4.9,
    deliveriesToday: 6,
    fuelLevel: 72,
    odometer: 12450,
  },
  {
    id: "driver-jose",
    name: "José Martínez",
    initials: "JM",
    phone: "+505 8888 6371",
    vehicle: "Yamaha YBR 125",
    vehiclePlate: "GR 18722",
    status: "disponible",
    rating: 4.8,
    deliveriesToday: 5,
    fuelLevel: 64,
    odometer: 8601,
  },
  {
    id: "driver-sofia",
    name: "Sofía Ramírez",
    initials: "SR",
    phone: "+505 8888 1920",
    vehicle: "Suzuki EN125",
    vehiclePlate: "GR 54120",
    status: "disponible",
    rating: 4.7,
    deliveriesToday: 4,
    fuelLevel: 88,
    odometer: 15487,
  },
  {
    id: "driver-pedro",
    name: "Pedro Torres",
    initials: "PT",
    phone: "+505 8888 7280",
    vehicle: "Bajaj Boxer 150",
    vehiclePlate: "GR 44018",
    status: "mantenimiento",
    rating: 4.6,
    deliveriesToday: 0,
    fuelLevel: 42,
    odometer: 10392,
  },
];

export const orders: DeliveryOrder[] = [
  {
    id: "DEL-20261006-A7K2",
    customer: "Carlos Mendoza",
    phone: "+505 8888 3278",
    address: "De la Catedral 2c al sur, Granada Centro",
    reference: "Casa blanca con portón negro",
    merchant: "Pollos Asados El Masayita",
    serviceType: "Delivery",
    status: "en_camino_cliente",
    priority: "alta",
    driver: "Luis Rodríguez",
    subtotal: 280,
    managementFee: 0,
    deliveryFee: 50,
    total: 330,
    paymentMethod: "Efectivo",
    receivedAmount: 500,
    changeDue: 170,
    createdAt: "10:18",
    otpRequired: true,
  },
  {
    id: "DEL-20261006-X9P4",
    customer: "Ana López",
    phone: "+505 8888 1104",
    address: "Barrio La Villa, Granada Sur",
    reference: "Frente a pulpería San Juan",
    merchant: "Farmacia Santa Ana",
    serviceType: "Mandado / compra",
    status: "pendiente_asignacion",
    priority: "media",
    subtotal: 420,
    managementFee: 35,
    deliveryFee: 70,
    total: 525,
    paymentMethod: "Transferencia",
    createdAt: "10:31",
    otpRequired: true,
  },
  {
    id: "DEL-20261006-B3R8",
    customer: "María Castillo",
    phone: "+505 8888 8291",
    address: "Calle La Calzada, Granada Centro",
    reference: "Hotel con recepción azul",
    merchant: "Supermercado La Unión",
    serviceType: "Paquete",
    status: "asignado",
    priority: "normal",
    driver: "José Martínez",
    subtotal: 0,
    managementFee: 20,
    deliveryFee: 50,
    total: 70,
    paymentMethod: "Efectivo",
    createdAt: "10:44",
    otpRequired: true,
  },
  {
    id: "DEL-20261006-M2K1",
    customer: "Jorge Silva",
    phone: "+505 8888 5210",
    address: "Carretera Nandaime, zona aledaña",
    reference: "Portón verde, antes de la gasolinera",
    merchant: "Repuestos Granada",
    serviceType: "Paquete",
    status: "confirmado",
    priority: "normal",
    subtotal: 0,
    managementFee: 30,
    deliveryFee: 100,
    total: 130,
    paymentMethod: "Transferencia",
    createdAt: "11:02",
    otpRequired: true,
  },
];

export const conversations: Conversation[] = [
  {
    id: "conversation-carlos",
    customer: "Carlos Mendoza",
    phone: "+505 8888 3278",
    preview: "Sí, confirma por favor. Pago con C$500.",
    time: "10:18",
    unread: 0,
    hasOrder: true,
    status: "abierta",
  },
  {
    id: "conversation-ana",
    customer: "Ana López",
    phone: "+505 8888 1104",
    preview: "Necesito unas medicinas de Farmacia Santa Ana.",
    time: "10:31",
    unread: 2,
    hasOrder: true,
    status: "abierta",
  },
  {
    id: "conversation-maria",
    customer: "María Castillo",
    phone: "+505 8888 8291",
    preview: "¿Pueden recoger un paquete en La Unión?",
    time: "10:44",
    unread: 1,
    hasOrder: true,
    status: "en_espera",
  },
  {
    id: "conversation-roberto",
    customer: "Roberto Vega",
    phone: "+505 8888 7640",
    preview: "Hola, quisiera saber cuánto cuesta enviar a Diriomo.",
    time: "09:58",
    unread: 1,
    hasOrder: false,
    status: "abierta",
  },
];

export const incidents: Incident[] = [
  {
    id: "INC-20261006-042",
    title: "Dirección incorrecta",
    orderId: "DEL-20261006-A7K2",
    customer: "Carlos Mendoza",
    driver: "Luis Rodríguez",
    priority: "media",
    status: "abierta",
    createdAt: "10:32",
    description: "El motorizado indica que no encuentra la dirección proporcionada.",
  },
  {
    id: "INC-20261006-041",
    title: "Vehículo averiado",
    orderId: "DEL-20261006-X9P4",
    customer: "Ana López",
    driver: "Pedro Torres",
    priority: "alta",
    status: "abierta",
    createdAt: "09:18",
    description: "La motocicleta perdió potencia durante el turno.",
  },
  {
    id: "INC-20261006-040",
    title: "Cliente no responde",
    orderId: "DEL-20261006-B3R8",
    customer: "María Castillo",
    driver: "Sofía Ramírez",
    priority: "normal",
    status: "en_revision",
    createdAt: "08:47",
    description: "Se realizaron tres intentos de contacto sin respuesta.",
  },
];

export const vehicles: Vehicle[] = [
  {
    id: "MOTO-007",
    plate: "GR 23981",
    label: "Honda CB125F · 2024",
    driver: "Luis Rodríguez",
    odometer: 12450,
    fuelType: "Gasolina regular",
    fuelLevel: 72,
    nextMaintenanceAt: 13500,
    status: "activo",
  },
  {
    id: "MOTO-012",
    plate: "GR 18722",
    label: "Yamaha YBR 125 · 2023",
    driver: "José Martínez",
    odometer: 8601,
    fuelType: "Gasolina regular",
    fuelLevel: 64,
    nextMaintenanceAt: 9000,
    status: "activo",
  },
  {
    id: "MOTO-014",
    plate: "GR 54120",
    label: "Suzuki EN125 · 2022",
    driver: "Sofía Ramírez",
    odometer: 15487,
    fuelType: "Gasolina regular",
    fuelLevel: 88,
    nextMaintenanceAt: 16500,
    status: "activo",
  },
  {
    id: "MOTO-018",
    plate: "GR 44018",
    label: "Bajaj Boxer 150 · 2021",
    driver: "Pedro Torres",
    odometer: 10392,
    fuelType: "Gasolina regular",
    fuelLevel: 42,
    nextMaintenanceAt: 10500,
    status: "mantenimiento",
  },
];

export const dashboardMetrics = [
  { label: "Pedidos activos", value: "12", detail: "4 esperan asignación", tone: "green" },
  { label: "Ingresos hoy", value: "C$ 8,460", detail: "+12.4% vs. ayer", tone: "blue" },
  { label: "Tiempo promedio", value: "34 min", detail: "Meta: menos de 40 min", tone: "amber" },
  { label: "Incidencias abiertas", value: "5", detail: "2 requieren atención", tone: "red" },
] as const;
