-- The Cloud API registration PIN is generated by the platform and encrypted at rest.
-- This lets a failed Meta provisioning step be retried without asking the business
-- owner to copy tokens, IDs, or PINs manually.
alter table public.whatsapp_accounts
  add column if not exists encrypted_registration_pin text;
